export default {
  DBT_START_VAR: "dbt-variable-start",
  DBT_END_VAR: "dbt-variable-end",
  DBT_START_TEMPLATE: 'dbt-template-start',
  DBT_START_MARKERS: 'dbt-start-markers',
  DBT_END_MARKERS: 'dbt-end-markers',
  DBT_END_TEMPLATE: 'dbt-template-end',
  WHITESPACE: "whitespace",
  WORD: "word",
  STRING: "string",
  RESERVED: "reserved",
  RESERVED_TOPLEVEL: "reserved-toplevel",
  RESERVED_NEWLINE: "reserved-newline",
  OPERATOR: "operator",
  OPEN_PAREN: "open-paren",
  CLOSE_PAREN: "close-paren",
  LINE_COMMENT: "line-comment",
  BLOCK_COMMENT: "block-comment",
  NUMBER: "number",
  PLACEHOLDER: "placeholder"
};
